### ISSUE TITLE
TODO code rendering

### ISSUE THREAD

**Issue by fatteneder** [fatteneder/MakieSlides.jl#14]
- [ ] Support line numbers
- [ ] Support line number styling (`Pygments` provides some attributes for this)
- [ ] Support all font style options provided by `Pygments`, unused so far: `mono, underline, sans, roman`.
- [ ] Figure out how to load custom styles into `Pygments` when install through `PyCall`.
